### ISSUE TITLE
Windows Defender on Windows 10 detecting as malware

### ISSUE THREAD

**Issue by keirlawson** [protyposis/LocalAudioBroadcast#2]
Using the latest release on Window 10 on my partner's laptop. Specifically: http://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fPocyx.gen!B!plock&threatid=-2147259709&enterprise=0

**Comment by protyposis** [comment]
Just scanned it on my Windows 10  and also did a [VirusTotal analysis](https://www.virustotal.com/en/file/cbebcbbfc65d39a33d9d5c8f32757e6c76cd21726b27942e6f903c0a476d178f/analysis/1451306856/): No reports of anything suspicious.

Thanks for reporting, but I'm afraid your trojan must be coming from somewhere else!
