### ISSUE TITLE
Poor sound quality

### ISSUE THREAD

**Issue by akaleeroy** [protyposis/LocalAudioBroadcast#3]
I use Foobar2000 with the [`foo_out_upnp`](https://www.foobar2000.org/components/view/foo_out_upnp) and [`foo_youtube`](https://fy.3dyd.com/home/) components, which enables me to play YouTube audio to my [UPnP renderer](http://www.daytonaudio.com/index.php/wfa02-multi-room-wi-fi-audio-adapter-for-ios-android-airplay-and-dlna.html)

I tested by listening to the same track from Foobar :vs: youtube.com on Chrome. 
Using LocalAudioBroadcast results in **degraded sound quality – all the bass is gone.**

FWIW the same problem occurs with [JamCast](https://getjamcast.com). It's like the System audio output is picked up wrong or something.

Thank you!

**Comment by ltguillaume** [comment]
What happens if you switch the default sampling frequency of your playback device to 44100Hz, or 48000Hz?

**Comment by akaleeroy** [comment]
I tried to switch from 44100Hz to **16bit 48000Hz (DVD Quality)** but no improvement.

**Later edit:** I managed to cast good quality audio with Foobar2000 with foo_out_upnp and foo_record and [VB Cable](https://www.vb-audio.com/Cable/). See [Stream system audio from soundcard to foobar](https://hydrogenaud.io/index.php/topic,104074.0.html)  
The `record://` stream in Foobar is **44100Hz 16bps 2ch**, so I don't think it's that.

**Comment by protyposis** [comment]
This is very strange, can't think of any reason why the bass would be gone unless you have an equalizer in your sound driver that is weirdly configured, i.e. adjusted to your built-in speakers in case it's a laptop.

The program basically just grabs the mixed sound output from Windows so there's nothing it could do to introduce or remove such effects. I wonder how Foobar grabs the stream.

**Comment by ltguillaume** [comment]
That would indeed make sense. I have a strange issue with my USB audio card driver which, instead of removing bass, removes a lot of high frequencies from the sound. When I using AC3 pass-through, that issue is gone. So there has to be some annoying filter in the driver that screws with the sound. What happens to the sound quality when using LAB while VB Cable is the default playback device?

**Comment by akaleeroy** [comment]
> What happens to the sound quality when using LAB while VB Cable is the default playback device?

It's good, I can't tell it apart from `foo_out_upnp`!

I listened more closely to LAB while Laptop speakers are the default playback device and the sound is louder, like it's clipped.

**Comment by ltguillaume** [comment]
Realtek sound chip? Perhaps something like this is enabled?
![](https://i.stack.imgur.com/p394K.png)

**Comment by akaleeroy** [comment]
Yep, Realtek soundcard, but I don't have a sound effects tab in their control panel.
I did however find a ☑ **Disable all sound effects** setting which I missed
![☑  Disable all sound effects](https://user-images.githubusercontent.com/4068718/36951097-0c03d450-2008-11e8-9b0e-8cb74e7ae74c.gif)
Problem solved :tada: 
Strange that Foobar ignored those. Anyway, thanks for your patience!
