### ISSUE TITLE
audio/L24

### ISSUE THREAD

**Issue by resom78** [protyposis/LocalAudioBroadcast#4]
Hi,

Your app is simply amazing, It's a shame it's not more famous!!
It's not an issue but more a request: Could you add the possibiliy to stream audio/L24 format because many renderers are now capable of this!
It would be nice to have this choice in the GUI!
Another point: is the WASAPI loopback capture based on the resolution of the sound card? It means if I set my output to 24bit/96KHz, the sound capture will be at this rate or do you resample everything to 16bit/44100Hz?

Thanks a lot!

**Comment by protyposis** [comment]
Hi, and thank you! I cannot say at this point if I am going to implement this, but I can answer the rest: It is definitely possible to implement, and yes the loopback capture is based on the sound card respectively the settings in the sound driver. Currently the sample rate is already directly used, so if you set your output to 96 kHz there is no resampling and it will be streamed with 96 kHz. The same would apply to the bit depth once the hardcoded L16 output is removed.

**Comment by protyposis** [comment]
Closing due to repo archival.
