### ISSUE TITLE
Reduce lag?

### ISSUE THREAD

**Issue by akaleeroy** [protyposis/LocalAudioBroadcast#5]
I use Foobar2000 with the [`foo_out_upnp`](https://www.foobar2000.org/components/view/foo_out_upnp) component to play audio to my [UPnP renderer](http://www.daytonaudio.com/index.php/wfa02-multi-room-wi-fi-audio-adapter-for-ios-android-airplay-and-dlna.html) and it barely has any lag. When using LocalAudioBroadcast there's a delay of a few seconds.

Can this lag be improved? Or is it fundamentally a different kind of situation when streaming from PC's audio? I'm curious because it occurred to me renderer is clearly capable of short lag.

Thanks!

**Comment by protyposis** [comment]
LocalAudioBroadcast sends the audio data to the renderer as fast as possible (except for a 100ms startup delay) so there is nothing done (e.g. buffering) that might introduce a lag. I noticed though that some UPnP renderers (e.g. Kodi) like to buffer 1 - 2 seconds of audio before rendering it, leading to the lag. 

I've basically made the same experience as you with `foo_upnp_out` but did unfortunately never find out what it does differently to avoid the buffering in the renderer.

**Comment by akaleeroy** [comment]
> Or is it fundamentally a different kind of situation when streaming from PC's audio? I'm curious because it occurred to me renderer is clearly capable of short lag.

I installed [MusicBee](https://getmusicbee.com/) with the [UPnP plugin](https://getmusicbee.com/addons/plugins/11/upnp-dlna-device-support/) and found out the following:

> ☐ **output as a continuous stream**
> [enables gapless playback and cross-fading **but output will lag** and the device will not be able to show current track information]

So I think the lag-free streaming is when you stream a bounded audio file to the device, and the laggy streaming is when the stream is continuous.

**Comment by protyposis** [comment]
Closing due to repo archival (and because the question is actually answered :)).
